### ISSUE TITLE
Notifying the user of an interval lower than that specified by the rqscheduler daemon

### ISSUE THREAD

**Issue by jmagnusson** [ui/rq-scheduler#28]
Today the default interval for rqscheduler is 60 seconds. If one passes an interval lower than that value it will still be accepted, but executed at the configured interval. Obvious if you read the code, but maybe not as clear to the user. Could the user somehow be notified of this?

If I'm not completely mistaken it's not possible to know the rqscheduler interval when creating the job; but perhaps the job could be replaced with another one by the rqscheduler daemon that just raises an exception explaining that the interval is lower than what's been configured?

**Comment by darkpixel** [comment]
Just got bit by this.

I have a job that needs to run every ~10-15 seconds.  Would there be any harm in dropping the daemon interval to a few seconds?

**Comment by selwin** [comment]
You can run rqscheduler with the --interval argument to specify your own interval.

**Comment by darkpixel** [comment]
Yeah--I saw the option.  I just wasn't sure based on the discussion above if it was 'smart' to do that.  ;)  Thanks.

**Comment by iankpconcentricsky** [comment]
So let me get this straight, if you run ./manage.py rqscheduler, there is an implicit landmine awaiting you in which no matter how you utilize the "interval" value in the API, you cannot possibly get it to function below 60 seconds?

Does the package not have the capacity to know the interval daemon, so that it can raise an exception that an impossible API request has been issued?

This is a strange and unfortunate, and super non-ergonomic issue.  You have to run a flag outside of your codebase to get your codebase to behave in a manner that you're explicitly asking it to. And nowhere is this even explicitly documented.  Instead, you get the docs informing you
` interval=60,                   # Time before the function is called again, in seconds`
but that's actually untrue.  This will not behave as documented if set below 60; unless you discover the magic necessary corresponding flag and tie the connection together as to why.

I advocate an exception is thrown, and improving the documentation/developer ergonomics.
