### ISSUE TITLE
setup periodic tasks with min, hour, day, month?

### ISSUE THREAD

**Issue by YAmikep** [ui/rq-scheduler#57]
Hi,

Is there a way to setup periodic tasks like crontabs:
- min (0 - 59)
- hour (0 - 23)
- day of month (1 - 31)
- month (1 - 12)
- day of week (0 - 6) (Sunday=0)

instead of defining the time of the first execution Time and the interval?

Thanks.

**Comment by nimasmi** [comment]
One implication of the way things are now, is that if the run daemon has been down for a period, then when it is resumed, the start time of subsequent jobs will be shifted by an amount related to the downtime.

https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L285

``` python
        if interval:
            # (expurgating a bit...)
            self.connection._zadd(self.scheduled_jobs_key,
                                  to_unix(datetime.utcnow()) + int(interval),
                                  job.id)
```
The new scheduled time is calculated as now + interval. As far as I understand it, this means that I can't reliably schedule a job for 10am every day. If my server is down from 0930-1030, subsequent instances of that job will happen at 1030 every day from then onward.

I'm also wondering whether the start time would naturally slip a little due to time taken to run the `.enqueue_jobs()` method.

**Comment by lechup** [comment]
@YAmikep #80 was merged into master. I think we can close this one?
