### ISSUE TITLE
Can I enqueue job at sub second level?

### ISSUE THREAD

**Issue by vinograd19** [ui/rq-scheduler#74]
To enqueue job you should run the code
`scheduler.enqueue_at(datetime(2020, 1, 1), func)`
What if I want to run the job after 0.012345 seconds? Can I do something like
`scheduler.enqueue_at(datetime(2020, 1, 1) + timedelta(microseconds=12345), func)` ?

**Comment by lost-theory** [comment]
Trigger times are stored with second resolution:

https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/utils.py#L10-L13

```
>>> calendar.timegm(datetime.datetime.now().utctimetuple())
1428411143
```

The latency of redis calls over the network is probably greater than 0.012345 seconds, so I don't think rq-scheduler is the right solution if you need subsecond accuracy. What is your use case for this?

**Comment by vinograd19** [comment]
My case is online game, I need to handle jobs with 0.2 seconds. 
So you say, that rq-scheduler has a restriction and I can't succeed?

**Comment by lost-theory** [comment]
Possibly, you'd be fighting two things:

1. Those `from_unix` / `to_unix` functions internal to rq-scheduler would need to be modified to return a floating point number, which may be a breaking change for current users, not sure.

2. Network round trip times for enqueuing and dequeueing a job could potentially be in the hundreds of milliseconds. I've even seen multi-second response times for simple redis operations when using AWS (Elasticache Redis). It depends how you're running redis. If you can run the redis server locally along with the rq processes that would give you better performance (and once you do that you can get another improvement by using a unix domain socket instead of TCP), but then you lose the ability to run workers on multiple machines.

So it may be a little tricky to use rq-scheduler for something like an online game. It's more often used for slow operations like sending emails, resizing images, making API calls, etc. in the background of a web application.

Is your game played in real-time? From what I've seen, real-time game servers hold a lot of connections open (e.g. using tornado, twisted, etc.) and do as much as they can in-process and in-memory. Using tornado or twisted you could get the subsecond responses via the event loop. See `callLater` in twisted and `call_later` in tornado.

**Comment by selwin** [comment]
The included `rqscheduler` script already supports floating point intervals so I'm open to adding floating point intervals to `interval` argument to `schedule()`. So if what you want to schedule a job that runs every 0.2 seconds, you would be able to do:
```python
scheduler.schedule(
    scheduled_time,
    my_function,
    repeat=5,
    interval=0.2
)
```
The above snippet should schedule the `my_function` to run 5 times at 0.2 seconds interval.
